spring:
  datasource:
    url: jdbc:h2:mem:todo;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8008
lumen:
  sql:
    log:
      enabled: true
      mode: INLINE
      log-on-execute: true
      include-elapsed: true
      include-row-count: true
      include-operation: true
      prefix: "SQL:"
